FROM ubuntu:24.04

## package setup
# -e 's/main universe restricted multiverse/main/' \
#RUN sed -i -e 's/^URIs:.*/URIs: http:\/\/ftp.riken.go.jp\/Linux\/ubuntu\//g' /etc/apt/sources.list.d/ubuntu.sources

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    dnsutils iputils-ping vim iproute2 tzdata less sudo \
    locales locales-all \
    rsyslog \
    telnet tcpdump tshark jq && \
    rm -rf /var/lib/apt/lists/*

ARG NETWORK=10.255

RUN sed -i '/imklog/s/^/# /g' /etc/rsyslog.conf && \
    echo '$EscapeControlCharactersOnReceive off' >> /etc/rsyslog.conf && \
    echo '$PreserveFQDN on' >> /etc/rsyslog.conf && \
    echo "*.* @${NETWORK}.0.253:514" >> /etc/rsyslog.conf

ENV LANG=en_US.UTF-8
ENV TZ=Asia/Tokyo
