FROM kasuyamofu/smtpbook-base:latest

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    postfix && \
    rm -rf /var/lib/apt/lists/*

RUN sed -i -E "/(enable_original_recipient|smtpd_tls_security_level|prepend_delivered_header|mail_spool_directory|mydestination|home_mailbox|mynetworks|inet_protocols)/d" /etc/postfix/main.cf && \
    echo "\
enable_original_recipient = no\n\
smtpd_tls_security_level = none\n\
prepend_delivered_header = \n\
mail_spool_directory = /var/mail/\n\
home_mailbox = Maildir/\n\
mydestination =\n\
mynetworks = 127.0.0.0/8 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16\n\
inet_protocols = ipv4" >> /etc/postfix/main.cf && \
    mkdir -p /var/mail && touch /var/log/postfix && \
    chown postfix:postfix /var/mail /var/log/postfix &&\
    chmod 777 /var/mail

ARG NETWORK
RUN echo "nameserver ${NETWORK}.0.254" > /var/spool/postfix/etc/resolv.conf
